### ISSUE TITLE
Enable CORS on your API?

### ISSUE THREAD

**Issue by bluejamesbond** [Sweetman/cs373-idb#73]
Hey guys, this is this the 4playdb team. Currently we are using a local copy of you data (since you don't have CORS) on our [page](http://4playdb.me/game/24024) to do some lookup...essentially a "widget" on our game page. Please enable CORS and if you think of a better usage of your API let us know! As you can see we are not very creative.

**Comment by bluejamesbond** [comment]
```
XMLHttpRequest cannot load http://hardcarry.me/api/abilities/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://4playdb.me' is therefore not allowed access.
24024:1 XMLHttpRequest cannot load http://hardcarry.me/api/champions/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://4playdb.me' is therefore not allowed access.
24024:1 XMLHttpRequest cannot load http://hardcarry.me/api/summoners/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://4playdb.me' is therefore not allowed access.
```

**Comment by clintburgos** [comment]
@bluejamesbond should be good now. try it and lemme know

**Comment by bluejamesbond** [comment]
@clintburgos its still not working. you can test it buy visiting our link and checking the Chrome console

**Comment by Sweetman** [comment]
@bluejamesbond any advice on how to fix this? we've tried changing flask cors settings a few times but no luck. is there something on the rackspace server itself we need to set up?

**Comment by clintburgos** [comment]
also I saw somewhere online you may be able to bypass it with angular's $request feature.
https://docs.angularjs.org/api/ngResource/service/$resource
maybe give that a try!

**Comment by Sweetman** [comment]
@bluejamesbond it is fixed

**Comment by mathew-kurian** [comment]
Sorry, I didn't see your messages in time. Anyways, glad its resolved. Thanks!
